dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # traj_controller:
  #   type: position_controllers/JointTrajectoryController
  #   joints:
  #     - arm_joint_1
  #     - arm_joint_3

  vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_2

  traj_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - arm_joint_1
    gains:
      arm_joint_1: {p: 1, d: 0.0, i: 0.0, i_clamp: 1.0}
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 5.0
      arm_joint_1:
        goal: 0.01
        trajectory: 0.07

dynamixel_control:
  serial_interface: /dev/ttyUSB0
  loop_frequency: 50
  cycle_time_error_threshold: 0.1
  baudrate: 3000000 # in bauds
  read_timeout: 0.05 # in seconds
  scan_timeout: 0.05 # in seconds
  # Configuration of the servos
  servos:
    arm_joint_1:
      # hardware ID of the actuator
      id: 2
      # offset to be added, in radians, to the position of an actuator
      offset: 3.14159265359 # in rad
      # max joint speed
      # it shoud NOT be used for actuators in velocity mode
      max_speed: 0.5 # in rad/s
  # default mode
  default_command_interface: velocity
